<section class="section section-newsletter-type-2">
  <div class="site-container">
    <div class="left-part">
      <div class="btn-wrap"><a href="#">NEWSLETTER SIGN UP</a></div>
      <div class="form form-newsletter-type-2">
        <form action="demo_actions/submit.php" method="post" id="test" class="ajax-submit">
          <div class="form-item form-type-text">
            <input type="text" class="form-text" name="first_name" placeholder="FIRST NAME"/>
          </div>
          <div class="form-item form-type-text">
            <input type="text" class="form-text" name="last_name" placeholder="LAST NAME"/>
          </div>
          <div class="form-item form-type-text">
            <input type="text" class="form-text" name="email" placeholder="EMAIL"/>
          </div>
          <div class="form-actions">
            <input type="submit" class="form-submit" value="SIGN-UP"/>
          </div>
        </form>
      </div>
    </div>
    <div class="right-part">
      <p>media inquiries <br/>
        <a href="mailto:media@nativeroots303.com">media@nativeroots303.com</a></p>
      <div class="social-menu">
        <ul>
          <li class="social-1"><a href="#"></a></li>
          <li class="social-2"><a href="#"></a></li>
          <li class="social-3"><a href="#"></a></li>
          <li class="social-4"><a href="#"></a></li>
        </ul>
      </div>
      <div class="btn-wrap style-black"><a href="#">sitemap</a></div>
    </div>
  </div>
</section>
<footer id="site-footer" class="site-footer">
  <div class="site-container">

  </div>
</footer>