<header id="site-header" class="site-header">
  <div class="site-container">
    <div class="logo"><a href="/"><img src="theme/images/logo.png" alt=""/></a></div>
    <div class="social-menu">
      <ul>
        <li class="social-1"><a href="#"></a></li>
        <li class="social-2"><a href="#"></a></li>
        <li class="social-3"><a href="#"></a></li>
        <li class="social-4"><a href="#"></a></li>
      </ul>
    </div>
    <nav class="nav">
      <a class="btn-nav" href="#"><span class="text"><span class="ico"></span></span></a>
      <div class="menu-wrapper">
        <ul class="menu">
          <li class="first expanded">
            <a href="/content/news" class="active">Culture</a>
            <ul class="menu">
              <li class="first leaf"><a href="/content/news" class="active">News</a></li>
              <li class="last leaf"><a href="/social">Social</a></li>
            </ul>
          </li>
          <li class="leaf"><a href="/locations">Locations</a></li>
          <li class="expanded">
            <a href="/cannabis" title="">Cannabis</a>
            <ul class="menu">
              <li class="first leaf"><a href="/categories/flower" title="">Flower</a></li>
              <li class="leaf"><a href="/categories/extracts" title="">Extract</a></li>
              <li class="leaf"><a href="/categories/edibles" title="">Edibles</a></li>
              <li class="last leaf"><a href="/categories/topical" title="">Topical</a></li>
            </ul>
          </li>
          <li class="leaf"><a href="/content/education">Education</a></li>
          <li class="leaf"><a href="/store">Gear</a></li>
          <li class="last leaf"><a href="/contact">Contact</a></li>
        </ul>
      </div>
      <a class="btn-location" href="#"></a>
    </nav>
    <div class="navigation">
      <ul class="menu">
        <li><a href="#">NATIVE
            REWARDS</a></li>
        <li><a class="cart-link" href="#">cart</a></li>
      </ul>
    </div>
  </div>
</header>