<!--[if (lt IE 9) & (!IEMobile)]>
<script async type="text/javascript" src="theme/js/lib/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="common/js/lib/jquery.min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.cookie.js"></script>
<script type="text/javascript" src="theme/js/lib/device.min.js"></script>
<!--<script type="text/javascript" src="theme/js/lib/jquery.simplr.smoothscroll.min.js"></script>-->
<script async type="text/javascript" src="theme/js/lib/cherry.parallax.js"></script>
<script async type="text/javascript" src="theme/js/lib/jquery.flexslider-min.js"></script>
<script type="text/javascript" src="theme/js/lib/select2.full.js"></script>
<script type="text/javascript" src="theme/js/lib/circles.min.js"></script>
<script type="text/javascript" src="theme/js/lib/soundmanager2.js"></script>
<script type="text/javascript" src="theme/js/lib/bar-ui.js"></script>
<script async type="text/javascript" src="theme/js/lib/masonry.pkgd.js"></script>
<script type="text/javascript" src="theme/js/js.js"></script>
<script type="text/javascript" src="demo_actions/form-submit.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.fancybox.pack.js"></script>